"""
MSA feature encoder for mini-alphafold (Phase 3).

Encodes a multiple sequence alignment (MSA) into a fixed-width feature tensor.
Works with real pre-aligned sequences or a pseudo-MSA generated by random mutation
of the query sequence when no real homologues are available.

Features (per sequence, per position)
--------------------------------------
  one_hot   — 22 dims  (VOCAB_SIZE: PAD/gap=0, UNK=1, A–Y=2–21)
  deletion  —  1 dim   (1.0 if the aligned position is a gap character '-', else 0.0)
  profile   — 22 dims  (per-position mean one-hot over all N sequences in the MSA)

  FEATURE_DIM = 22 + 1 + 22 = 45

Profile captures per-position amino-acid frequencies across homologues — the MSA
co-evolutionary signal that AF2's Evoformer exploits. Gap positions contribute
index-0 to the profile, so the first element of the profile is the gap fraction.

Public API
----------
  MSAFeatures                         — output dataclass
  MSAEncoder                          — encodes list[str] → (N, L, 45)
  generate_pseudo_msa(seq, n, rate)   — random-mutation pseudo-MSA
  encode_single_sequence(seq)         — backward-compat single-seq wrapper
  FEATURE_DIM                         — exported constant (45)

Backward compatibility
----------------------
  A single query sequence can always be wrapped via encode_single_sequence(),
  which inserts a trivial N=1 MSA.  Downstream modules can treat the first
  row (index 0) as the query representation.

Notes
-----
  All sequences in the MSA must be pre-aligned to the same length L.
  Gap characters ('-' or '.') are mapped to index 0 (PAD_IDX).
  Unknown amino acids are mapped to UNK_IDX=1, the same as the tokeniser.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Optional

import torch
import torch.nn.functional as F
from torch import Tensor

from src.data.protein_dataset import (
    AA_TO_IDX,
    IDX_TO_AA,
    PAD_IDX,
    UNK_IDX,
    VOCAB_SIZE,
    tokenize,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ONE_HOT_DIM: int = VOCAB_SIZE      # 22
DELETION_DIM: int = 1
FEATURE_DIM: int = ONE_HOT_DIM + DELETION_DIM + ONE_HOT_DIM   # 45

_GAP_CHARS = frozenset("-.")


# ---------------------------------------------------------------------------
# Output dataclass
# ---------------------------------------------------------------------------

@dataclass
class MSAFeatures:
    """Encoded MSA feature tensor with provenance metadata.

    Attributes:
        features:    (N_seq, L, FEATURE_DIM) float32 tensor.
                     Axis-0 index 0 is always the query sequence.
        n_seq:       Number of sequences (including query).
        seq_len:     Aligned sequence length L.
        is_pseudo:   True when generated by generate_pseudo_msa().
    """
    features: Tensor         # (N, L, 45)
    n_seq: int
    seq_len: int
    is_pseudo: bool = False

    @property
    def one_hot(self) -> Tensor:
        """(N, L, 22) — per-sequence per-position one-hot."""
        return self.features[..., :ONE_HOT_DIM]

    @property
    def deletion(self) -> Tensor:
        """(N, L, 1) — 1.0 where position is a gap."""
        return self.features[..., ONE_HOT_DIM:ONE_HOT_DIM + DELETION_DIM]

    @property
    def profile(self) -> Tensor:
        """(N, L, 22) — per-position amino-acid frequency (broadcast over N)."""
        return self.features[..., ONE_HOT_DIM + DELETION_DIM:]

    def query_features(self) -> Tensor:
        """(L, 45) — features for the query sequence (row 0)."""
        return self.features[0]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _tokenize_aligned(sequence: str) -> tuple[Tensor, Tensor]:
    """Tokenize an aligned sequence, returning tokens and a deletion mask.

    Gap characters '-' and '.' are mapped to PAD_IDX=0.
    All other characters follow the standard tokenise() logic.

    Returns:
        tokens:    (L,) long tensor — token indices.
        del_mask:  (L,) float32 tensor — 1.0 where position is a gap.
    """
    tokens = []
    is_gap = []
    for ch in sequence:
        if ch in _GAP_CHARS:
            tokens.append(PAD_IDX)
            is_gap.append(1.0)
        else:
            tokens.append(AA_TO_IDX.get(ch.upper(), UNK_IDX))
            is_gap.append(0.0)
    return (
        torch.tensor(tokens, dtype=torch.long),
        torch.tensor(is_gap, dtype=torch.float32),
    )


# ---------------------------------------------------------------------------
# MSA encoder
# ---------------------------------------------------------------------------

class MSAEncoder:
    """Encodes a list of pre-aligned amino-acid strings into MSA features.

    The sequences must all have the same length L (the alignment length).
    The query sequence must be the first element of the list.

    Args:
        device: Target device for the output tensor.

    Usage::

        enc = MSAEncoder()
        msa = ["ACDEFGHIK", "A-DEFGHIK", "ACDEFGHIK"]  # already aligned, L=9
        features = enc.encode(msa)
        print(features.features.shape)   # (3, 9, 45)
    """

    def __init__(self, device: Optional[torch.device] = None) -> None:
        self.device = device or torch.device("cpu")

    def encode(self, sequences: list[str]) -> MSAFeatures:
        """Encode an MSA into feature tensors.

        Args:
            sequences: List of aligned amino-acid strings (may contain '-'/'.').
                       sequences[0] is treated as the query.

        Returns:
            MSAFeatures with .features of shape (N_seq, L, FEATURE_DIM).

        Raises:
            ValueError: If the list is empty or sequences differ in length.
        """
        if not sequences:
            raise ValueError("sequences must be non-empty.")
        lengths = {len(s) for s in sequences}
        if len(lengths) != 1:
            raise ValueError(
                f"All sequences must be the same length (aligned). "
                f"Got lengths: {sorted(lengths)}"
            )

        N = len(sequences)
        L = len(sequences[0])

        all_tokens: list[Tensor] = []
        all_del: list[Tensor] = []
        for seq in sequences:
            tok, del_mask = _tokenize_aligned(seq)
            all_tokens.append(tok)
            all_del.append(del_mask)

        tokens_mat = torch.stack(all_tokens, dim=0)    # (N, L) long
        del_mat    = torch.stack(all_del,   dim=0)     # (N, L) float32

        # One-hot: (N, L, 22)
        one_hot = F.one_hot(tokens_mat, num_classes=ONE_HOT_DIM).float()

        # Deletion: (N, L, 1)
        deletion = del_mat.unsqueeze(-1)

        # Profile: mean one-hot over sequences, broadcast back to (N, L, 22)
        profile_1d = one_hot.mean(dim=0, keepdim=True)        # (1, L, 22)
        profile = profile_1d.expand(N, -1, -1)                # (N, L, 22)

        features = torch.cat([one_hot, deletion, profile], dim=-1)  # (N, L, 45)

        return MSAFeatures(
            features=features.to(self.device),
            n_seq=N,
            seq_len=L,
            is_pseudo=False,
        )

    def encode_single(self, sequence: str) -> MSAFeatures:
        """Encode a single query sequence as a trivial N=1 MSA.

        No homologues — the profile equals the one-hot of the query, and
        deletion is all-zero.  Use this for backward-compatible single-sequence
        inference.
        """
        result = self.encode([sequence])
        result.is_pseudo = False   # it is genuinely a single sequence
        return result


# ---------------------------------------------------------------------------
# Pseudo-MSA generator
# ---------------------------------------------------------------------------

_AA_LIST = list(AA_TO_IDX.keys())   # 20 standard amino acids


def generate_pseudo_msa(
    query: str,
    n_sequences: int = 16,
    mutation_rate: float = 0.15,
    seed: Optional[int] = None,
) -> list[str]:
    """Generate a pseudo-MSA by randomly mutating the query sequence.

    Each synthetic homologue is produced by independently replacing each
    residue with a random standard amino acid with probability `mutation_rate`.
    No gaps are introduced — all sequences have the same length as the query.

    This is a minimal stand-in for real evolutionary homologues. It provides
    non-trivial profile features (diversity grows with mutation_rate) without
    requiring external MSA search tools.

    Args:
        query:         Query amino-acid string (may contain non-standard chars).
        n_sequences:   Number of homologous sequences to generate (excluding
                       the query itself). The returned list has n_sequences+1
                       entries with the query at index 0.
        mutation_rate: Per-residue substitution probability (default 0.15,
                       ~evolutionary distance of remote homologues).
        seed:          Optional RNG seed for reproducibility.

    Returns:
        List of n_sequences+1 strings, all of length len(query).
        sequences[0] is always the unchanged query.
    """
    rng = random.Random(seed)
    msa = [query]
    for _ in range(n_sequences):
        mutated = []
        for aa in query:
            if rng.random() < mutation_rate:
                mutated.append(rng.choice(_AA_LIST))
            else:
                mutated.append(aa)
        msa.append("".join(mutated))
    return msa


# ---------------------------------------------------------------------------
# Backward-compat convenience wrapper
# ---------------------------------------------------------------------------

def encode_single_sequence(sequence: str) -> MSAFeatures:
    """Encode one sequence with no MSA (N=1 trivial MSA).

    The feature tensor has shape (1, L, 45).  The profile equals the
    one-hot of the query, and the deletion channel is all zero.

    This is the drop-in replacement for callers that have no MSA data:
    downstream Evoformer-style modules can treat index-0 as the query row.
    """
    return MSAEncoder().encode_single(sequence)


# ---------------------------------------------------------------------------
# Example / smoke-test — run with:  python -m src.data.msa_encoder
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("=" * 60)
    print("MSA Encoder — smoke test")
    print("=" * 60)

    # ---- 1. Single-sequence (backward-compat path) ----
    query = "ACDEFGHIKLMNPQRSTVWY"
    feat_single = encode_single_sequence(query)
    assert feat_single.features.shape == (1, len(query), FEATURE_DIM), \
        f"Expected (1, {len(query)}, {FEATURE_DIM}), got {feat_single.features.shape}"
    assert feat_single.deletion.sum() == 0, "No gaps expected for ungapped query"
    print(f"[1] Single-sequence: features {feat_single.features.shape}  (PASS)")

    # ---- 2. Pseudo-MSA generation ----
    msa_seqs = generate_pseudo_msa(query, n_sequences=7, mutation_rate=0.2, seed=42)
    assert len(msa_seqs) == 8, f"Expected 8 seqs, got {len(msa_seqs)}"
    assert msa_seqs[0] == query, "First sequence must be the unchanged query"
    assert all(len(s) == len(query) for s in msa_seqs), "All seqs must share length"
    print(f"[2] Pseudo-MSA:  {len(msa_seqs)} seqs x L={len(query)}  (PASS)")

    # ---- 3. Full MSA encoding ----
    enc = MSAEncoder()
    feat = enc.encode(msa_seqs)
    assert feat.features.shape == (8, len(query), FEATURE_DIM)
    assert feat.n_seq == 8
    assert feat.seq_len == len(query)
    assert not feat.is_pseudo
    print(f"[3] Encoded MSA:  {feat.features.shape}  (PASS)")

    # ---- 4. One-hot sanity: argmax should recover query tokens ----
    from src.data.protein_dataset import AA_TO_IDX as A2I
    expected_tokens = [A2I.get(aa, UNK_IDX) for aa in query]
    query_oh = feat.one_hot[0]                   # (L, 22)
    recovered = query_oh.argmax(dim=-1).tolist()
    assert recovered == expected_tokens, f"Token mismatch: {recovered} vs {expected_tokens}"
    print(f"[4] One-hot argmax recovers query tokens  (PASS)")

    # ---- 5. Profile sums to 1 at each position ----
    profile_sum = feat.profile[0].sum(dim=-1)    # (L,)
    assert torch.allclose(profile_sum, torch.ones(len(query)), atol=1e-5), \
        "Profile rows should sum to 1"
    print(f"[5] Profile sums to 1 at each position  (PASS)")

    # ---- 6. Gap / deletion handling ----
    gapped_seqs = ["ACDEF", "A-DEF", "ACD-F"]   # two gap positions
    feat_gap = enc.encode(gapped_seqs)
    assert feat_gap.deletion[0].sum() == 0, "Query has no gaps"
    assert feat_gap.deletion[1, 1, 0] == 1.0, "seq1 position 1 is a gap"
    assert feat_gap.deletion[2, 3, 0] == 1.0, "seq2 position 3 is a gap"
    print(f"[6] Gap/deletion encoding  (PASS)")

    # ---- 7. Feature slice properties ----
    assert feat.one_hot.shape  == (8, len(query), ONE_HOT_DIM)
    assert feat.deletion.shape == (8, len(query), DELETION_DIM)
    assert feat.profile.shape  == (8, len(query), ONE_HOT_DIM)
    assert feat.query_features().shape == (len(query), FEATURE_DIM)
    print(f"[7] Slice properties  (PASS)")

    print()
    print(f"All tests passed. FEATURE_DIM = {FEATURE_DIM}")
    print()
    print("Usage example:")
    print("  from src.data.msa_encoder import generate_pseudo_msa, MSAEncoder")
    print("  msa = generate_pseudo_msa('ACDEFGHIK', n_sequences=15)")
    print("  feat = MSAEncoder().encode(msa)")
    print("  print(feat.features.shape)  # (16, 9, 45)")
